In [160]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,classification_report

**KNN Classifier**

In [161]:
#load_dataset
df=sns.load_dataset('iris')
df.head

<bound method NDFrame.head of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [162]:
#split dataset
X=df.drop('species',axis=1)
y=df['species']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [163]:
#Train the model
model=KNeighborsClassifier(n_neighbors=3)
model.fit(X_train,y_train)

#predict
y_pred=model.predict(X_test)

#evaluate
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9666666666666667
[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       1.00      0.92      0.96        13
   virginica       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



**KNN Regressor**

In [164]:
#load dataset
data=sns.load_dataset('titanic')
data.head()


survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [165]:
#impute missing values
data.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [166]:
#impute missing values
data['age'].fillna(data['age'].median(),inplace=True)
data['embarked'].fillna(data['embarked'].mode()[0],inplace=True)
data['embark_town'].fillna(data['embark_town'].mode()[0],inplace=True)
data.drop('deck',axis=1,inplace=True)
data.isnull().sum()

C:\Users\Laptop\AppData\Local\Temp\ipykernel_7384\2022473223.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['age'].fillna(data['age'].median(),inplace=True)
C:\Users\Laptop\AppData\Local\Temp\ipykernel_7384\2022473223.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

Fo

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [167]:
Q1 = data[['age', 'fare']].quantile(0.25)
Q3 = data[['age', 'fare']].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

condition = (
    (data['age'] >= lower_bound['age']) & (data['age'] <= upper_bound['age']) &
    (data['fare'] >= lower_bound['fare']) & (data['fare'] <= upper_bound['fare'])
)

data = data[condition].reset_index(drop=True)


In [168]:
#encode the data using for loop
for col in data.columns:
    if data[col].dtype=='object' or data[col].dtype=='category':
        data[col]=LabelEncoder().fit_transform(data[col])


In [169]:
#split dataset
X=data.drop('survived',axis=1)
y=data['survived']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)


In [170]:
#Train the model
model=KNeighborsClassifier(n_neighbors=3)
model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [171]:
#predict
y_pred=model.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7793103448275862
[[83  9]
 [23 30]]
              precision    recall  f1-score   support

           0       0.78      0.90      0.84        92
           1       0.77      0.57      0.65        53

    accuracy                           0.78       145
   macro avg       0.78      0.73      0.75       145
weighted avg       0.78      0.78      0.77       145



In [172]:
#save the model
import pickle
pickle.dump(model,open('C:/Users/Laptop/ML project/KNN_model.pkl','wb'))